name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Set up Android NDK
        uses: android-actions/setup-ndk@v1
        with:
          ndk_version: r26b
          cmake_version: '3.22.1'

      - name: Build with cargo
        run: cargo build --target aarch64-linux-android --release
